---
# Application to deploy
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mytodo
spec:
  replicas: 3 # tells deployment to run 3 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: mytodo
        tier: frontend
    spec:
      # imagePullSecrets:
      # - name: private-registry-secret
      containers:
      - name: mytodo
        image: <region>.icr.io/<namespace>/mytodo:1.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m     # 250 millicores = 1/4 core
            memory: 128Mi # 128 MB
          limits:
            cpu: 500m
            memory: 384Mi
        volumeMounts:
          - mountPath: /opt/service-bind # Mount the "service-bind-volume" volume into the pod.
            name: service-bind-volume
      volumes:
        - name: service-bind-volume
          secret:
            defaultMode: 420
            secretName: binding-mytodo-cloudant
---
# Service to expose frontend
apiVersion: v1
kind: Service
metadata:
  name: mytodo
  labels:
    app: mytodo
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8080 # Internal Port
    nodePort: 31513
  selector:
    app: mytodo
    tier: frontend
